config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pics#index'

  resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :find_pic, only: [:show, :edit, :update, :destroy]
  def index
    @pics = Pic.all.order("created_at DESC")
  end

  def new
    @pic = current_user.pics.build
  end

  def create
    @pic = current_user.pics.build(pic_params)

    if @pic.save
      redirect_to @pic, notice: "It was posted!"
    else
      render 'new'
    end

  end

  def show
  end

  def update
    if @pic.update(pic_params)
      redirect_to @pic, notice: "Pic was updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @pic.destroy
    redirect_to root_path
  end

  private
  def pic_params
    params.require(:pic).permit(:title, :description)
  end

  def find_pic
    @pic = Pic.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Picastagram
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    -flash.each do |name, msg|
      =content_tag :div, msg, class: "alert alert-info"
    = yield

app/views/pics/_form.html.haml
= simple_form_for @pic, html: { multipart: true } do |f|

  - if @pic.errors.any?
    #errors
      %h2
        = pluralize(@pics.errors.count, "error")
        prevented this pic from saving
        %ul
          - @pic.errors.full_messages.each do |msg|
            %li= msg

  .form-group
    = f.input :title, input_html: {class: 'form-control'}
  .form-group
    = f.input :description, input_html: {class: 'form-control'}
  .form-group
    = f.submit "Submit", input_html: {class: 'btn btn-info btn-lg'}

app/views/pics/edit.html.haml
%h1 Edit Pic

= render 'form'

= link_to "Cancel", pic_path

app/views/pics/index.html.haml
- @pics.each do |pic|
  %h2= link_to pic.title, pic

= link_to "Drop a Pic", new_pic_path

app/views/pics/new.html.haml
%h1 Post Pic
= render 'form'

= link_to "Back" , root_path

app/views/pics/show.html.haml
%h1= @pic.title
%p= @pic.description
%p
Pic by
= @pic.user.email

= link_to "Back", root_path
= link_to "Edit", edit_pic_path
= link_to "Delete", pic_path, method: :delete, data: { confirm: "Are you sure?" }